// This file is auto-generated by Bld.Libnl.Generator
// Do not edit manually

using System.Runtime.InteropServices;
using Bld.Libnl.Types;

namespace Bld.Libnl;

public static partial class Nl80211AttributeParser
{
    /// <summary>
    /// Check if custom parser exists for the attribute
    /// </summary>
    private static partial bool HaveCustomParser(Nl80211Attribute attr);

    /// <summary>
    /// Parse attribute using custom parser
    /// </summary>
    private static partial INl80211AttributeValue? ParseAttributeCustom(Nl80211Attribute attr, IntPtr nla);

    /// <summary>
    /// Parse nl80211 attribute based on its type
    /// </summary>
    public static unsafe INl80211AttributeValue? ParseAttribute(Nl80211Attribute attr, IntPtr nla)
    {
        if (nla == IntPtr.Zero)
            return null;

        if(HaveCustomParser(attr))
        {
            return ParseAttributeCustom(attr, nla);
        }

        return attr switch
        {
            Nl80211Attribute.NL80211_ATTR_WIPHY => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_NAME => ParseString(nla),
            Nl80211Attribute.NL80211_ATTR_WIPHY_TXQ_PARAMS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_WIPHY_FREQ => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_CHANNEL_TYPE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_EDMG_CHANNELS => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_EDMG_BW_CONFIG => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_CHANNEL_WIDTH => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_CENTER_FREQ1 => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_CENTER_FREQ1_OFFSET => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_CENTER_FREQ2 => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_RETRY_SHORT => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_RETRY_LONG => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_FRAG_THRESHOLD => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_RTS_THRESHOLD => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_COVERAGE_CLASS => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_DYN_ACK => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_IFTYPE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_IFINDEX => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_IFNAME => ParseString(nla),
            Nl80211Attribute.NL80211_ATTR_MAC => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_PREV_BSSID => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_KEY => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_KEY_DATA => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_KEY_IDX => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_KEY_CIPHER => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_KEY_DEFAULT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_KEY_SEQ => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_KEY_TYPE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_BEACON_INTERVAL => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_DTIM_PERIOD => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_BEACON_HEAD => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_BEACON_TAIL => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_STA_AID => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_FLAGS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_STA_LISTEN_INTERVAL => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_SUPPORTED_RATES => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_STA_PLINK_ACTION => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_TX_POWER_SETTING => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_TX_POWER => Nl80211AttributeValue.FromS16(LibNlNative.nla_get_s16(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_VLAN => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_MESH_ID => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MPATH_NEXT_HOP => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_REG_ALPHA2 => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_REG_RULES => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_BSS_CTS_PROT => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_BSS_SHORT_PREAMBLE => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_BSS_SHORT_SLOT_TIME => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_BSS_BASIC_RATES => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_BSS_HT_OPMODE => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_MESH_CONFIG => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_SUPPORT_MESH_AUTH => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_HT_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MGMT_SUBTYPE => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_IE => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_SCAN_FREQUENCIES => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_SCAN_SSIDS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_SSID => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_AUTH_TYPE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_REASON_CODE => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_FREQ_FIXED => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_TIMED_OUT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_USE_MFP => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_FLAGS2 => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_CONTROL_PORT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_CONTROL_PORT_ETHERTYPE => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_CONTROL_PORT_NO_ENCRYPT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_CONTROL_PORT_OVER_NL80211 => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_PRIVACY => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_STATUS_CODE => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_CIPHER_SUITE_GROUP => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WPA_VERSIONS => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_PID => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_4ADDR => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_PMKID => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_DURATION => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_COOKIE => Nl80211AttributeValue.FromU64(LibNlNative.nla_get_u64(nla)),
            Nl80211Attribute.NL80211_ATTR_TX_RATES => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_FRAME => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FRAME_MATCH => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_PS_STATE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_CQM => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_LOCAL_STATE_CHANGE => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_AP_ISOLATE => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_TX_POWER_SETTING => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_TX_POWER_LEVEL => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_FRAME_TYPE => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_ANTENNA_TX => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_ANTENNA_RX => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_MCAST_RATE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_OFFCHANNEL_TX_OK => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_KEY_DEFAULT_TYPES => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_WOWLAN_TRIGGERS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_STA_PLINK_STATE => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_MEASUREMENT_DURATION => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_MEASUREMENT_DURATION_MANDATORY => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_MESH_PEER_AID => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_SCHED_SCAN_INTERVAL => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_REKEY_DATA => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_SCAN_SUPP_RATES => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_HIDDEN_SSID => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_IE_PROBE_RESP => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_IE_ASSOC_RESP => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_ROAM_SUPPORT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_STA_WME => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_SCHED_SCAN_MATCH => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_TX_NO_CCK_RATE => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_TDLS_ACTION => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_TDLS_DIALOG_TOKEN => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_TDLS_OPERATION => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_TDLS_SUPPORT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_TDLS_EXTERNAL_SETUP => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_TDLS_INITIATOR => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_DONT_WAIT_FOR_ACK => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_PROBE_RESP => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_DFS_REGION => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_DISABLE_HT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_NOACK_MAP => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_INACTIVITY_TIMEOUT => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_BG_SCAN_PERIOD => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_WDEV => Nl80211AttributeValue.FromU64(LibNlNative.nla_get_u64(nla)),
            Nl80211Attribute.NL80211_ATTR_USER_REG_HINT_TYPE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_AUTH_DATA => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_VHT_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_SCAN_FLAGS => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_P2P_CTWINDOW => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_P2P_OPPPS => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_LOCAL_MESH_POWER_MODE => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_MAC_ADDRS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_STA_CAPABILITY => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_STA_EXT_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_SPLIT_WIPHY_DUMP => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_DISABLE_VHT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_MDID => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_IE_RIC => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_CRIT_PROT_ID => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_MAX_CRIT_PROT_DURATION => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_PEER_AID => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_CH_SWITCH_COUNT => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_CH_SWITCH_BLOCK_TX => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_CSA_IES => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_CNTDWN_OFFS_BEACON => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_CNTDWN_OFFS_PRESP => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_STA_SUPPORTED_CHANNELS => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_STA_SUPPORTED_OPER_CLASSES => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_HANDLE_DFS => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_OPMODE_NOTIF => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_VENDOR_ID => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_VENDOR_SUBCMD => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_VENDOR_DATA => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_QOS_MAP => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MAC_HINT => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_WIPHY_FREQ_HINT => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_TDLS_PEER_CAPABILITY => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_SOCKET_OWNER => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_CSA_C_OFFSETS_TX => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_USE_RRM => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_TSID => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_USER_PRIO => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_ADMITTED_TIME => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_SMPS_MODE => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_OPER_CLASS => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_MAC_MASK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_WIPHY_SELF_MANAGED_REG => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_NETNS_FD => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_SCHED_SCAN_DELAY => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_REG_INDOOR => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_PBSS => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_BSS_SELECT => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_STA_SUPPORT_P2P_PS => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_MU_MIMO_FOLLOW_MAC_ADDR => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_NAN_MASTER_PREF => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_BANDS => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_NAN_FUNC => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_FILS_KEK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FILS_NONCES => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MULTICAST_TO_UNICAST_ENABLED => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_BSSID => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_SCHED_SCAN_RELATIVE_RSSI => Nl80211AttributeValue.FromS8(LibNlNative.nla_get_s8(nla)),
            Nl80211Attribute.NL80211_ATTR_TIMEOUT_REASON => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_FILS_ERP_USERNAME => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FILS_ERP_REALM => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FILS_ERP_NEXT_SEQ_NUM => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_FILS_ERP_RRK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FILS_CACHE_ID => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_PMK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_PMKR0_NAME => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_SCHED_SCAN_MULTI => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_EXTERNAL_AUTH_SUPPORT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_TXQ_LIMIT => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_TXQ_MEMORY_LIMIT => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_TXQ_QUANTUM => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_HE_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FTM_RESPONDER => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_TIMEOUT => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_PEER_MEASUREMENTS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_AIRTIME_WEIGHT => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_SAE_PASSWORD => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_TWT_RESPONDER => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_HE_OBSS_PD => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_VLAN_ID => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_HE_BSS_COLOR => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_TID_CONFIG => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_CONTROL_PORT_NO_PREAUTH => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_PMK_LIFETIME => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_PMK_REAUTH_THRESHOLD => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_RECEIVE_MULTICAST => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_WIPHY_FREQ_OFFSET => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_SCAN_FREQ_KHZ => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_HE_6GHZ_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_FILS_DISCOVERY => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_UNSOL_BCAST_PROBE_RESP => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_S1G_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_S1G_CAPABILITY_MASK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_SAE_PWE => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_RECONNECT_REQUESTED => null,
            Nl80211Attribute.NL80211_ATTR_SAR_SPEC => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_DISABLE_HE => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_OBSS_COLOR_BITMAP => Nl80211AttributeValue.FromU64(LibNlNative.nla_get_u64(nla)),
            Nl80211Attribute.NL80211_ATTR_COLOR_CHANGE_COUNT => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_COLOR_CHANGE_COLOR => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_COLOR_CHANGE_ELEMS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_MBSSID_CONFIG => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_MBSSID_ELEMS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_RADAR_BACKGROUND => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_AP_SETTINGS_FLAGS => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_EHT_CAPABILITY => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_DISABLE_EHT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_LINKS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_LINK_ID => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_MLD_ADDR => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_SUPPORT => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_MAX_NUM_AKM_SUITES => null,
            Nl80211Attribute.NL80211_ATTR_EML_CAPABILITY => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_PUNCT_BITMAP => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_MAX_HW_TIMESTAMP_PEERS => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_HW_TIMESTAMP_ENABLED => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_EMA_RNR_ELEMS => Nl80211AttributeValue.FromNested(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_LINK_DISABLED => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_BSS_DUMP_INCLUDE_USE_DATA => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_TTLM_DLINK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_TTLM_ULINK => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_ASSOC_SPP_AMSDU => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_VIF_RADIO_MASK => Nl80211AttributeValue.FromU32(LibNlNative.nla_get_u32(nla)),
            Nl80211Attribute.NL80211_ATTR_SUPPORTED_SELECTORS => ParseBinary(nla),
            Nl80211Attribute.NL80211_ATTR_MLO_RECONF_REM_LINKS => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_EPCS => ParseFlag(nla),
            Nl80211Attribute.NL80211_ATTR_ASSOC_MLD_EXT_CAPA_OPS => Nl80211AttributeValue.FromU16(LibNlNative.nla_get_u16(nla)),
            Nl80211Attribute.NL80211_ATTR_WIPHY_RADIO_INDEX => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_S1G_LONG_BEACON_PERIOD => Nl80211AttributeValue.FromU8(LibNlNative.nla_get_u8(nla)),
            Nl80211Attribute.NL80211_ATTR_S1G_SHORT_BEACON => Nl80211AttributeValue.FromNested(nla),
            _ => null
        };
    }

    private static unsafe INl80211AttributeValue? ParseBinary(IntPtr nla)
    {
        var len = LibNlNative.nla_len(nla);
        if (len <= 0)
            return null;

        var data = new byte[len];
        var dataPtr = LibNlNative.nla_data(nla);
        Marshal.Copy(dataPtr, data, 0, len);
        return Nl80211AttributeValue.FromBinary(data);
    }

    private static unsafe INl80211AttributeValue? ParseString(IntPtr nla)
    {
        var strPtr = LibNlNative.nla_get_string(nla);
        if (strPtr == IntPtr.Zero)
            return null;

        var str = Marshal.PtrToStringUTF8(strPtr);
        return str != null ? Nl80211AttributeValue.FromString(str) : null;
    }

    private static unsafe INl80211AttributeValue? ParseFlag(IntPtr nla)
    {
        // Flags are present or absent, if we have nla it means flag is set
        return Nl80211AttributeValue.FromU8(1);
    }
}
